### ISSUE TITLE
For loop for ggplot not working

### ISSUE THREAD

**Issue by ChristianKammler** [lvanhee/COVID-sim#130]
I was not able to get the for loop for the stacked bar chart to work.  It worked for creating a multiple page PDF document but for some reason, it didn´t work for the ggplot. I have tried multiple variations of the loop.

**Comment by ChristianKammler** [comment]
When I changed the values manually, it worked however.

**Comment by lvanhee** [comment]
I had a similar issue, particularly when running it from the Rstudio. Here
were the fixes I found online and through experience:
-add the output in a print statement
-add a delay of 1 second after each plot
-use the script
-be patient, imagine it's NetLogo ;-)

Le mer. 6 mai 2020 à 12:51, ChristianKammler <notifications@github.com> a
écrit :
