### ISSUE TITLE
Error in setup? Requested 993 random agents from a set of only 234 agents

### ISSUE THREAD

**Issue by ChristianKammler** [lvanhee/COVID-sim#146]
When altering the existing behaviorspace for the smart testing scenario, I set the "ratio-population-randomly-tested-daily"  to 1 with "#available-tests" to 1500. I kept the setup and go command. However, after starting the behaviorspace run, the following error occurses after a few ticks:
Requested 993 random agents from a set of only 234 agents.
error while observer running N-OF
  called by procedure PERFORM-DAILY-TESTING-PUBLIC-MEASURE (/Users/christiankammler/Documents/May1905/COVID-sim/simulation_model/public_measures/testing.nls)
  called by procedure APPLY-ACTIVE-MEASURES (/Users/christiankammler/Documents/May1905/COVID-sim/simulation_model/public_measures/public_measures.nls)
  called by procedure GO
  called by procedure __EVALUATOR

**Comment by rmellema** [comment]
I think this issue is fixed at around the same time that you found it. `n-of` has been replaced in the function `perform-daily-testing-public-measure` by `up-to-n-of` which does not throw this error.
