### ISSUE TITLE
Error: [unimplemented essential-shop essential shopping]

### ISSUE THREAD

**Issue by mijkehurk** [lvanhee/COVID-sim#20]
Appears at tick 30, full error code:
[unimplemented essential-shop essential shopping]
error while person 188 running ERROR
  called by procedure CAN-BE-DONE-WITH-A-DEPENDABLE-PERSON? (/Users/mijke/Documents/PhD/COVID simulation/COVID-sim/activity_model.nls)
  called by procedure MY-AVAILABLE-ACTIVITY-DESCRIPTORS (/Users/mijke/Documents/PhD/COVID simulation/COVID-sim/people_decision.nls)
  called by procedure MY-PREFERRED-AVAILABLE-ACTIVITY-DESCRIPTOR (/Users/mijke/Documents/PhD/COVID simulation/COVID-sim/people_decision.nls)
  called by procedure SELECT-ACTIVITY (/Users/mijke/Documents/PhD/COVID simulation/COVID-sim/people_decision.nls)
  called by procedure PERFORM-ACTIVITY (/Users/mijke/Documents/PhD/COVID simulation/COVID-sim/activity_model.nls)
  called by procedure PERFORM-PEOPLE-ACTIVITIES (/Users/mijke/Documents/PhD/COVID simulation/COVID-sim/activity_model.nls)
  called by procedure GO
  called by Button 'go'

**Comment by lvanhee** [comment]
Some parts of the procedure were missing. It should be fixed by now. 
Thank you for reporting.
