### ISSUE TITLE
Non-essential-shops don't seem to interact

### ISSUE THREAD

**Issue by MelchiorUU** [lvanhee/COVID-sim#32]
I levied 100% tax, made goods maximum expensive and still their captial or their stock doesn't change. Seems they aren't doing anything.

**Comment by lgludescher** [comment]
This was because the measure 'total-lockdown' was active. Putting it as none you can see the effects on non-essential-shops.

**Comment by MelchiorUU** [comment]
Ah, so I’ve done all my calibrations while the system was in lockdown mode… I’ll go and redo them then.

--Alexander

**Comment by rmellema** [comment]
Can this issue be closed?

**Comment by MelchiorUU** [comment]
No, just found a new issue:

They still need to lose capital due to expenses, like wages or fixed cost. We didn't implement fixed cost, thus they shouldn't be able to fire people. But they still need to pay people 100%  *When the wage pay measure isn't active*, then it become 100& - ratio of government.

**Comment by lgludescher** [comment]
Now non essential shops pay wages even if they are closed.

**Comment by MelchiorUU** [comment]
They didn't 8 days ago. Has this been fixed now?
