### ISSUE TITLE
Population is larger than #total-population

### ISSUE THREAD

**Issue by MelchiorUU** [lvanhee/COVID-sim#34]
See title.
#total-population 250 -> 272 population in sim,
201 -> 218, 500 -> 547

**Comment by lvanhee** [comment]
Seems like it raises from the generation
 @lgludescher , can you have a look at that, please?

**Comment by lgludescher** [comment]
I'm on it.

**Comment by lgludescher** [comment]
I couldn't reproduce this. Total people created is always equal to what is defined in the #total-population input.

**Comment by lgludescher** [comment]
Actually there's no bug. It was just a confusion because the value shown in the graph does not reflect the exact number of people.
