### ISSUE TITLE
Update economy values in the baseline

### ISSUE THREAD

**Issue by lvanhee** [lvanhee/COVID-sim#35]
* ratio-school-subsidy:  0.07 -> 0.02
* ratio-hospital-subsidy: 0.18 -> 0.26
* ratio-retirees-subsidy: 0.37 -> 0.32
* ratio-students-subsidy: 0.30 -> 0.38

* price-of-rations: 2.1 -> 2.5

* ratio-tax-on-non-essential-shops: 0.52 -> 0.60 [seems to be bugged]

* goods-production-by-work-performed: 10 -> 7
* unit-price-of-goods: 1.8 -> 2.4

* starting-amount-of-capital-retired: 30 -> 40
* starting-amount-of-capital-students: 35 -> 30
(since when do students have more money than boomers? 😉)

* food-safety always seems to go down. But i don't know if this is bad?
* same for luxury, always goes down

**Comment by ChristianKammler** [comment]
This could be cleared in my opinion, because this was set when lockdown occured and the baseline should be set when no meassures are in place.

**Comment by rmellema** [comment]
I think this is also overruled by #42 which set up the values that Alexander send out later.
