### ISSUE TITLE
Division by zero.

### ISSUE THREAD

**Issue by MelchiorUU** [lvanhee/COVID-sim#36]
Made all taxes 0, made days of rations bought 0,.

Division by zero.
error while person 326 running /
  called by procedure FOOD-SAFETY-NEED-SATISFACTION (D:\phd\ASSOCC\COVID-sim\need_definition.nls)
  called by procedure MY-EXPECTED-DISCOUNTED-SATISFACTION-GAIN-FOR-FOOD-SAFETY-AFTER-HAVING-PLAYED (D:\phd\ASSOCC\COVID-sim\need_management.nls)
  called by procedure MY-EXPECTED-DISCOUNTED-SATISFACTION-GAIN-FOR-SAFETY-AFTER-HAVING-PLAYED (D:\phd\ASSOCC\COVID-sim\need_management.nls)
  called by procedure MY-CURRENT-PREVALENCE-OF-SAFETY-NEEDS (D:\phd\ASSOCC\COVID-sim\need_management.nls)
  called by procedure GLOBAL-PREVALENCE-OF (D:\phd\ASSOCC\COVID-sim\need_management.nls)
  called by procedure MY-PREFERRED-AVAILABLE-ACTIVITY-DESCRIPTOR (D:\phd\ASSOCC\COVID-sim\people_decision.nls)
  called by procedure SELECT-ACTIVITY (D:\phd\ASSOCC\COVID-sim\people_decision.nls)
  called by procedure PERFORM-ACTIVITY (D:\phd\ASSOCC\COVID-sim\activity_model.nls)
  called by procedure PERFORM-PEOPLE-ACTIVITIES (D:\phd\ASSOCC\COVID-sim\activity_model.nls)
  called by procedure GO
  called by Button '1 Week Run'

**Comment by rmellema** [comment]
Closed by #44
