### ISSUE TITLE
Selecting different households in GUI does not change people distribution

### ISSUE THREAD

**Issue by mijkehurk** [lvanhee/COVID-sim#38]
The contribution stays the same even when different household configurations are selected, namely 42 children, 80 students, 114 workers, 64 retired (300 total).

**Comment by lgludescher** [comment]
@lvanhee this is because everything is based on the preset-scenario. Currently there are only preset-scenarios that use Scandinavian distribution of households.

**Comment by lgludescher** [comment]
Solved. Now there's a preset-scenario called "generic-baseline" that allows changing the households distribution.
