### ISSUE TITLE
Loading scenario -> forced to 220 population

### ISSUE THREAD

**Issue by MelchiorUU** [lvanhee/COVID-sim#50]
See title.

I am writing my scenario in scenario.nls, but once I load my scenario in the interface it is forced to 220 population even if is set it to something else. If I set the population (#total-population) in the command line does work. 

I expect there is somewhere in the code that forces it to 220 in the scenario setting procedure.

**Comment by lgludescher** [comment]
As far as I know, according to recent changes regarding the households model it's not possible to set the total population anymore. Now you have to set the number of households (#households) and the total population will be defined from that.

**Comment by lvanhee** [comment]
The matter seems clarified, I believe.
