### ISSUE TITLE
[Needs model] Weird definition of some needs (mixed survival & financial survival?)

### ISSUE THREAD

**Issue by lvanhee** [lvanhee/COVID-sim#53]
to-report expected-undiscounted-safety-needs-satisfaction-increase-for-playing [ad]
  report weighted-mean (list 
    (expected-undiscounted-compliance-needs-satisfaction-increase-for-playing ad) 
    (expected-undiscounted-survival-needs-satisfaction-increase-for-playing ad) ;;this line is very strange. Shouldn't it be financial-survival, here?
    (expected-undiscounted-risk-avoidance-needs-satisfaction-increase-for-playing ad)
  ) 
  (list my-importance-for-compliance-needs my-importance-for-survival-needs my-importance-for-risk-avoidance-needs)
end

**Comment by rmellema** [comment]
That is an old function, that should actually no longer be used. So this is from when `survival` was still `food-safety`
