### ISSUE TITLE
[Bug] Economic scenario 3: non-essential-shops do not lose capital

### ISSUE THREAD

**Issue by MelchiorUU** [lvanhee/COVID-sim#59]
Running economic scenario 3, lockdown, gives the following graph:

![image](https://user-images.githubusercontent.com/59364209/78383617-f90d3700-75d8-11ea-8dbf-5548f78cd34d.png)

The blue line of non-essential-shops is not moving. This implicates that the non-essential-shops are not spending any money, as they have no income.

The expected behaviour is that their capital would be going down due to paying wages of their employees. (and once their have no more capital that they can no longer pay employees, thus employees no longer have an income)

**Comment by lgludescher** [comment]
Solved.
