### ISSUE TITLE
[Bug] household profiles reset to 100 households on "set-values"

### ISSUE THREAD

**Issue by Zara84** [lvanhee/COVID-sim#62]
The current scenario in the UI includes selecting household profiles, but if I choose any and run set-values, the setup reverts to 100 households. If I don't run set-values, the number of households does not change to 100, but the distribution is always the same, regardless of which household profile I select. 
I need to either have set-values behave properly, or have setup set the household distribution properly.

**Comment by lvanhee** [comment]
Hi @Zara84 ,
The behaviour you introduce here is a desired feature as pre-set scenarios define the number of households.
A bug however being that "no-action-scandinavia-5K" does not create 5K agents (the scenario is to be fixed here; I'm on it at the moment).
An easy way out for you lies in setting a scenario, then changing the #households value.

Is this answer enough for you?

**Comment by lvanhee** [comment]
Updated code.

**Comment by Zara84** [comment]
I think I can get it to behave now. Thank!
