### ISSUE TITLE
Numbers of graphs don't add up?

### ISSUE THREAD

**Issue by MelchiorUU** [lvanhee/COVID-sim#63]
See the following graphs of a lockdown run:

![image](https://user-images.githubusercontent.com/59364209/78811084-9f867d00-79c9-11ea-9a60-3e8f209d509b.png)

The amount of people working seems to be less (~20) than the amount of people that are at workplaces (and shops, uni, etc) combined (~50). I would expect that the total amount of people working would be equal to the amount of people who are at worklplaces. Is this a bug?

**Comment by rmellema** [comment]
There were some monitors for locations missing, but they have been added in the meantime, so I'm closing this issue
