### ISSUE TITLE
Model throws division by zero errors during runs

### ISSUE THREAD

**Issue by rmellema** [lvanhee/COVID-sim#86]
Sometimes, the model throws a division by zero error in the reporter `ratio-sick-personel`, which is used by `hospital-effectiveness`, which determines the number of beds and therefore influences the needs. This is quite a problem for people running behaviourspace experiments, since that can lead to runs where every step breaks.
I think this is caused by all the workers at some gathering point (in this case the hospital) dying, which means that the `count hired-workers` is zero.

**Comment by ChristianKammler** [comment]
Solved
