### ISSUE TITLE
Add explanation to the model

### ISSUE THREAD

**Issue by billlyzhaoyh** [lvanhee/COVID-sim#87]
Hi Ivan, this looks really cool and I am wondering if you can add more information to model info so I can understand this model better?

I am fairly new to ABM but I have been working on this project https://www.aiforgoodsimulator.com/ which is using modelling to help NGOs within refugee camps and refugee camp-like settings. I am looking into adapting this model for my use case. It will be great if you or your colleague can spare some help!

**Comment by rmellema** [comment]
Hi Billy,

There is more information available about the project and the simulation at the web page https://simassocc.org, there you can find more information on the model, including an ODD. 
I hope that helps!
