### ISSUE TITLE
Error when trying to export run

### ISSUE THREAD

**Issue by MelchiorUU** [lvanhee/COVID-sim#88]
After a run I pressed "export" and got the following error:

The file C:\phd\Corona\COVID-sim\simulation_model\output\done.csv cannot be found
error while observer running FILE-PRINT
  called by procedure SAVE-WORLD-STATE (C:\phd\Corona\COVID-sim\simulation_model\utils.nls)
  called by Button 'export'

org.nlogo.nvm.RuntimePrimitiveException: The file C:\phd\Corona\COVID-sim\simulation_model\output\done.csv cannot be found
 at org.nlogo.prim.file._fileprint.perform(primitives.scala:122)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
 at scala.util.control.Exception$Catch.apply(Exception.scala:228)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.1.1
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) 64-Bit Server VM 1.8.0_202 (Oracle Corporation; 1.8.0_202-b08)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.8
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: covid-sim

05:54:52.062 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
05:54:52.009 DirtyEvent (org.nlogo.app.codetab.TemporaryCodeTab) AWT-EventQueue-0
05:54:52.009 DirtyEvent (org.nlogo.app.codetab.TemporaryCodeTab) AWT-EventQueue-0
05:54:51.931 RuntimeErrorEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
05:54:51.931 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:54:51.931 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
05:54:51.931 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
05:54:51.931 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
05:54:51.931 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
05:54:51.931 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0

**Comment by lvanhee** [comment]
Weird, netlogo should try to create a file when there is none, but it does not.
Could you please:
-try the updated version
-check whether "export-world import-scenario-name" works
-create a file and try the updated version

**Comment by MelchiorUU** [comment]
I’ll try it tomorrow!

On 18 Apr 2020, at 23:46, lvanhee <notifications@github.com> wrote:

﻿

Weird, netlogo should try to create a file when there is none, but it does not.
Could you please:
-try the updated version
-check whether "export-world import-scenario-name" works
-create a file and try the updated version

**Comment by MelchiorUU** [comment]
Doesn't work... but:

- I manually created a folder called "output".
- And now it works!

So either making the folder in netlogo or in the repository should fix it.

**Comment by rmellema** [comment]
Netlog also has access to the traditional file selectors, we could alternatively use those instead of a string in the interface. 
@lvanhee do you want me set that up instead? Then people can just put the files wherever they want, even outside of the directory with the simulation.

**Comment by lvanhee** [comment]
Yes, please go for it.

Le mar. 21 avr. 2020 à 15:31, René Mellema <notifications@github.com> a
écrit :

**Comment by rmellema** [comment]
This is now implemented by commit f4f74b2, so now export asks the user where to safe, and import asks the user where to load from.
