### ISSUE TITLE
Try recursive and preemptive contact tracing

### ISSUE THREAD

**Issue by Sjors** [lvanhee/COVID-sim#93]
If I understand the tracking app simulation correctly, when a person is tested, all their "contacts" are instantly notified, and then they get tested. It's not clear if this is recursive: are contacts of contacts also notified?

https://github.com/lvanhee/COVID-sim/blob/3ebc07435113115e0b749497c915e0788fa84ec2/simulation_model/contagion.nls#L44-L55

https://github.com/lvanhee/COVID-sim/blob/c64574ec8b6eecffbf1db16ec0c83204089e8813/simulation_model/epistemic_model.nls#L38-L52

In the real world (which also has delays between asking for a test, doing the actual test, getting the result and notifying contacts), contact tracing can be done recursively. People can be asked / ordered to self-isolate until they themselves are tested. You could simulate this for different levels of recursion; maybe ask Singapore authorities how far they trace.

Also, if one member of a household uses the app, it stands to reason that the entire household is isolated, regardless of whether they're using the app. The same goes for friends who are contacted the old fashioned way without an app.

(also, is `previous-contacts-met` limited to the past two weeks?)

**Comment by lvanhee** [comment]
Hello Sjors,

Thank you for this (other) very interesting observation. As a quick answer, yes, this is recursive, see the line:
` ask people-recorded-by-my-recording-app with [last-test-tick < ticks and not has-been-tested-infected?] [perform-test] `
`previous-contacts-met` is set as an external variable, you can set any number of days (I don't remember what is its value by default).

You raise interesting modelling questions that could be added in the model. It falls out of the scope of the github, but here  is a reference to the TODO list for modelling: https://docs.google.com/document/d/13GrsWF8w5QHBp272eMRxQz4cC4eYZjxmNMX-9s_OF_M/edit
Please feel free to join and send a mail to the SIMASSOCC group: simassocc@googlegroups.com (owner: Virginia Dignum <virginia@cs.umu.se>), so we can prioritize it and decide when/whether to process it.

Here is a reference to the (ongoing/to be done/on-demand) modelling documentation of testing: https://docs.google.com/document/d/1hx_su_4xolkG2vDQPYxb2HiBC9Y8IQin4VHhkBFQHoQ/edit

Thanks again for this great proposal,
Loïs

**Comment by lvanhee** [comment]
The recommandations have been added to the TODO list for models. Please feel free to get in touch with us for more information.
