### ISSUE TITLE
Lognormal distribution in e.g. risk of contagion?

### ISSUE THREAD

**Issue by Sjors** [lvanhee/COVID-sim#94]
Currently the risk of contagion is a throw of the dice, which for a large enough simulation is a normal distribution:

https://github.com/lvanhee/COVID-sim/blob/7bc15b7bc9b840470d0457e26d363fd304f325ec/simulation_model/contagion.nls#L106-L112

What happens when you introduce a lognormal distribution, especially with large populations where super spreader events matter? Some properties of virus spread are better described with a lognormal than with a normal distributions, see e.g. https://www.mdpi.com/2077-0383/9/2/538

> Our results show that the incubation period falls within the range of 2–14 days with 95% confidence and has a mean of around 5 days when approximated using the best-fit lognormal distribution.

**Comment by lvanhee** [comment]
Hello Sjors,

Thank you for your in-depth intervention. This discussion is quite interesting but it should first be treated from a modelling standpoint, whereas github is more for implementation concerns. It might be worth being investigated, but first the principles need to be through through.

Our main contact point is Frank Dignum, could you please send him a mail with your concerns? dignum@cs.umu.se

Best regards,
Loïs Vanhée

**Comment by lvanhee** [comment]
The request has been added to the modelling todo list.

**Comment by Sjors** [comment]
Thanks, I might sign up for that doc later...
