### ISSUE TITLE
Agents social distance while the measure is off?

### ISSUE THREAD

**Issue by MelchiorUU** [lvanhee/COVID-sim#97]
See below:

![image](https://user-images.githubusercontent.com/59364209/79793042-3ea75f00-8350-11ea-9420-c10ed4ff435c.png)

It says that the social distancing value is True while the measure is off. I interpret this as a social distancing agent while it shouldn't. Is this correct? If so this seems to be a bug.

[edit] this is from the economic scenario 1.

**Comment by rmellema** [comment]
An agent can decide to apply social distancing even if it is not required or asked of them, same as that they can decide to not social distance if it is asked of them. 
We'll be running some experiments on this today/tomorrow, so the number might change a bit, but that they can social distance while it is not enforced is not a bug.
